@echo off

::   *-----------------------------------------------------------------------------*
::   | This file is writing my optimized version of the fake-sandbox.ps1 script to |
::   | your autostart directory. After you log in to your user account this script |
::   | will launch automatically and start as ususal.                              |
::   |                                                                             |
::   | Like the original file, the startup script will simulate fake processes of  |
::   | analysis sandbox/VM software some malware will try to evad                  |
::   | This just spawn ping.exe with different names (wireshark.exe, vboxtray.exe, |
::   | etc...)                                                                     |
::   *-----------------------------------------------------------------------------*--------*                                                           
::   | Hint: This is only for your user account. It will open at Startup and there is no    |
::   | way to stop the processes but to download the full file and execute the stop action. |
::   *--------------------------------------------------------------------------------------*
::   |P.S: I know this is not the most elegant implementation, but hey... it works.         | 
::   *--------------------------------------------------------------------------------------*

::  Please enter your desired fake processes here:
SET @proc="wireshark.exe","vmacthlp.exe","VBoxService.exe","VBoxTray.exe","procmon.exe","ollydbg.exe","vmware-tray.exe","idag.exe","ImmunityDebugger.exe"
TITLE Fake-Sandbox Installer
SET @v=1.0

:: Just some nice user interface things
echo Fake-Sandbox installation script. Version %@v%, 2016.
echo Visit https://www.github.com/aperture-diversion/fake-sandbox/ for updates and fixes.
echo.
echo.
echo You are about to install the fake-sandbox script to your computer (autostart). Click to continue...
echo.
pause

:: Creation of the file that will execute the Powershell script upon startup
del "%appdata%\Microsoft\Windows\Start Menu\Programs\Startup\fake-sandbox.bat"
ECHO :: This file is autogenerated by the fake-processes-installer.bat (Version %@v%)>>"%appdata%\Microsoft\Windows\Start Menu\Programs\Startup\fake-sandbox.bat"
ECHO :: available on https://www.github.com/aperture-diversion/fake-sandbox/ .>>"%appdata%\Microsoft\Windows\Start Menu\Programs\Startup\fake-sandbox.bat"
ECHO.>>"%appdata%\Microsoft\Windows\Start Menu\Programs\Startup\fake-sandbox.bat"
ECHO @echo off>>"%appdata%\Microsoft\Windows\Start Menu\Programs\Startup\fake-sandbox.bat"
ECHO TITLE Fake-Sandbox is starting...>>"%appdata%\Microsoft\Windows\Start Menu\Programs\Startup\fake-sandbox.bat"
ECHO.>>"%appdata%\Microsoft\Windows\Start Menu\Programs\Startup\fake-sandbox.bat"
ECHO Powershell.exe -executionpolicy remotesigned -File "%appdata%\Aperture Diversion\fake-sandbox.ps1">>"%appdata%\Microsoft\Windows\Start Menu\Programs\Startup\fake-sandbox.bat"
ECHO exit>>"%appdata%\Microsoft\Windows\Start Menu\Programs\Startup\fake-sandbox.bat"

:: Creation of the fake-sandbox.ps1 script in the new directory %appdata%\Aperture Diversion\
del "%appdata%\Aperture Diversion\fake-sandbox.ps1"
mkdir "%appdata%\Aperture Diversion\"
ECHO # This file is autogenerated by the fake-processes-installer.bat (Version %@v%)>>"%appdata%\Aperture Diversion\fake-sandbox.ps1"
ECHO # available on https://www.github.com/aperture-diversion/fake-sandbox/ .>>"%appdata%\Aperture Diversion\fake-sandbox.ps1"
ECHO.>>"%appdata%\Aperture Diversion\fake-sandbox.ps1"
ECHO $fakeProcesses = @(%@proc%)>>"%appdata%\Aperture Diversion\fake-sandbox.ps1"
ECHO.>>"%appdata%\Aperture Diversion\fake-sandbox.ps1"
ECHO     $tmpdir = [System.Guid]::NewGuid().ToString()>>"%appdata%\Aperture Diversion\fake-sandbox.ps1"   
ECHO     $binloc = Join-path $env:temp $tmpdir>>"%appdata%\Aperture Diversion\fake-sandbox.ps1"
ECHO.>>"%appdata%\Aperture Diversion\fake-sandbox.ps1"
ECHO     New-Item -Type Directory -Path $binloc>>"%appdata%\Aperture Diversion\fake-sandbox.ps1"
ECHO     $oldpwd = $pwd>>"%appdata%\Aperture Diversion\fake-sandbox.ps1"
ECHO     Set-Location $binloc>>"%appdata%\Aperture Diversion\fake-sandbox.ps1"
ECHO.>>"%appdata%\Aperture Diversion\fake-sandbox.ps1"
ECHO     foreach ($proc in $fakeProcesses) {>>"%appdata%\Aperture Diversion\fake-sandbox.ps1"
ECHO       Copy-Item c:\windows\system32\ping.exe "$binloc\$proc">>"%appdata%\Aperture Diversion\fake-sandbox.ps1"
ECHO.>>"%appdata%\Aperture Diversion\fake-sandbox.ps1"
ECHO       Start-Process ".\$proc" -WindowStyle Hidden -ArgumentList "-t -w 3600000 -4 1.1.1.1">>"%appdata%\Aperture Diversion\fake-sandbox.ps1"
ECHO       write-host "[+] Process $proc spawned">>"%appdata%\Aperture Diversion\fake-sandbox.ps1"
ECHO     }>>"%appdata%\Aperture Diversion\fake-sandbox.ps1"
ECHO.>>"%appdata%\Aperture Diversion\fake-sandbox.ps1"
ECHO     Set-Location $oldpwd>>"%appdata%\Aperture Diversion\fake-sandbox.ps1"

echo.
cls
echo.
echo Done, all files have been created. This should work after you relogin.
echo.  
pause
exit